name: sync
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn

      - uses: actions/checkout@v3
        if: github.event_name == 'push'
        with:
          path: data
          ref: data

      - name: Install deps
        run: yarn
      - name: Fetch messages
        run: yarn messages

      - name: Deploy
        if: github.event_name != 'pull_request'
        run: |
          cd data
          git config user.name "Doramanjyu"
          git config user.email "24859285+Doramanjyu@users.noreply.github.com"
          git add .
          git commit -m "Deploy ${GITHUB_SHA}" --allow-empty
          git push origin data
