name: sync
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

environments:
  AWS_REGION: ap-northeast-1

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn

      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          path: data
          ref: data

      - name: Install deps
        run: yarn
      - name: Fetch messages
        env:
          MESSAGES_CSV_URL: ${{ secrets.MESSAGES_CSV_URL }}
        run: yarn messages

      - name: Deploy
        if: github.event_name != 'pull_request'
        run: |
          cd data
          git config user.name "Doramanjyu"
          git config user.email "24859285+Doramanjyu@users.noreply.github.com"
          git add .
          git commit -m "Deploy ${GITHUB_SHA}" --allow-empty
          git push origin data

      - name: Configure AWS credentials
        if: github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload
        if: github.event_name != 'pull_request'
        run: s3 sync --size-only data/messages/ s3://jebagrad2023web/messages/
